name: Deploy to Ubuntu VM Instance and Kubernetes

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Execute remote SSH commands to deploy
              uses: appleboy/ssh-action@v1.2.5
              with:
                command_timeout: 60m
                host: ${{ secrets.VM_HOST }}
                username: ${{ secrets.VM_USER }}
                key: ${{ secrets.VM_SSH_KEY }}
                script: |
                    set -euo pipefail

                    # 1. Check if Minikube is running
                    if ! minikube status >/dev/null 2>&1; then
                        minikube start --cpus=4 --memory=7168 --driver=docker --container-runtime=docker
                    fi

                    minikube kubectl -- wait --for=condition=Ready nodes --all --timeout=300s
                    echo "Minikube OK"
                    minikube status

                    # 2. Navigate to the application folder
                    cd /home/ubuntu/.projects/OllamaModelTesterWeb/

                    # 3. Pull latest changes from main branch
                    git fetch origin main
                    git reset --hard origin/main
                    git clean -fd

                    # 4. Delete backend and frontend clusters
                    minikube kubectl -- delete deployment ollama-tester-backend
                    minikube kubectl -- delete service ollama-tester-backend-service

                    minikube kubectl -- delete deployment ollama-tester-frontend
                    minikube kubectl -- delete service ollama-tester-frontend-service

                    # 5. Cleanup images
                    docker system prune -a -f
                    minikube ssh -- "docker system prune -a -f"

                    minikube kubectl -- get deployments
                    minikube kubectl -- get services
                    minikube kubectl -- get pods

                    # 6. Build images and apply deployments from the folder
                    minikube image build -t ollama-tester-backend:latest ./backend/.
                    minikube kubectl -- apply -f ./backend/k8s/backend-deployment.yaml

                    minikube image build -t ollama-tester-frontend:latest ./frontend/.
                    minikube kubectl -- apply -f ./frontend/k8s/frontend-deployment.yaml

                    # 7. Verify deployment is successful
                    minikube kubectl -- rollout status deployment/ollama-tester-backend --timeout=300s
                    minikube kubectl -- rollout status deployment/ollama-tester-frontend --timeout=180s

                    minikube kubectl -- get deployments
                    minikube kubectl -- get services
                    minikube kubectl -- get pods
